title: Tegan's Website
author: Tegan Lamoureux
description: Thoughts, projects, portfolio, and cats.
github: https://github.com/tegan-lamoureux
about: Thoughts and projects.

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/tegan-lamoureux"
    - icon: fa-linkedin
      link: "https://linkedin.com/in/tegan-lamoureux"
    - icon: fa-twitter
      link: "https://twitter.com/tegan_lamoureux"
    - icon: fa-linux
      link: "https://www.archlinux.org"

share:
  twitter_username: tegan_lamoureux

urls:
    - text: Resume
      url: /resume/
    - text: About Me
      url: /about/
    - text: Contact
      url: /contact/

baseurl: ""
paginate: 10
per_page: 10
paginate_path: "/page:num/"
markdown: kramdown
gems:
    - jekyll-paginate
    - jekyll-gist